spring:
  application:
    name: binance-copy-leader
binance:
  # 복사거래(리더) 전용 설정
  copy-trading:
    key: w2Mjp6tyOru1XrHifbJuXP1BdQoOP4Tcadd9EzupezMy17KzKeF8FHZsrz3XWOOU
    secret: uwOGRzQnvRso5DXKEBvARURkd8bVXxXwpqaozc6DqoSJJn|W1TRDBWa5iyauZfD9
    base-url: https://api.binance.com

  # 선물 거래(포지션 조회·주문) 전용 설정
  futures:
    key: nTuuDj6KrrOjtLwmCSfdToYIvlo9sVYZv1MIUtoCNQUbhbLvavOgIMDRwb6yI1KD
    secret: VqAZ7pUeXE2ocmMHxT97VivqhYRmJ9roEzU8BLNQtr8uhOzizh021DVRadOe65Qh
    base-url: https://fapi.binance.com
telegram:
  bot-token: 7262627991:AAG_opD2AjY-PSDr9rmJzWuY5S6anPoh-uI
  chat-id: 6412822135


